### ISSUE TITLE
How to persist DTree?

### ISSUE THREAD

**Issue by mohas** [gyrdym/ml_algo#123]
Hi, when I made a DecisionTreeClassification how can I presist it's model so we can reuse it in my next sessions because training in DTree takes a lot of time?

**Comment by gyrdym** [comment]
@mohas Hi, thank you for opening the issue, I will add the desired functionality to the classifier as soon as possible - it's one of the things that I planned to do first. Unfortunately, right now you can't save the trained model. Just keep tracking this issue, I'll write when the functionality is ready.

**Comment by mohas** [comment]
Coming from other programming languages I thought I could just binary serialize the dtree class itself, but apparently this is not easily doable in dart

**Comment by gyrdym** [comment]
@mohas sorry for such a big delay, finally I've added the desired functionality to DecisionTreeClassifier. You can use the following example as a guide:

````dart
final featuresForPrediction = Matrix.fromList([
  [200,  300, 1, 0, 0, 10, -40],
  [190, -500, 1, 0, 0, 11, -31],
  [2563, 16,  0, 0, 1, 22,  50],
  [5598, 14,  0, 1, 0, 99, 100],
]);

final targetName = 'col_8';

final classifier = DecisionTreeClassifier(fakeDataSet, targetName, minError: 0.3, minSamplesCount: 1, maxDepth: 3);

final testFileName = 'test/classifier/decision_tree_classifier/serialized_classifier.json';

await classifier.saveAsJson(testFileName);
````

And to restore the classifier:
````dart
final file = await File(testFileName);
final json = await file.readAsString();
final restoredClassifier = DecisionTreeClassifier.fromJson(json);
````

You may visit the appropriate [unit test](https://github.com/gyrdym/ml_algo/blob/master/test/classifier/decision_tree_classifier/decision_tree_classifier_test.dart) to see it in action.
