### ISSUE TITLE
Data persistence for Knn model

### ISSUE THREAD

**Issue by jurrdb** [gyrdym/ml_algo#131]
Hi, what would be the best way to persist a knn model without recreating it every time? Is this also serializable, or does this model always need data to compute predictions lazily?

**Comment by gyrdym** [comment]
Hi @jurrdb, thank you for creating the issue.

You're right, you always need data to make predictions, but I can add the possibility to serialize the model at least for the model's fields such as `targetName`, `dtype`, `kernel`, it might be useful.

**Comment by jurrdb** [comment]
Hello @gyrdym, and thanks for your response. I don't think that will be necessary (for me) when the data is still needed whenever the model is used. That was the reason for opening the issue for me.

**Comment by gyrdym** [comment]
@gyrdym I understand, anyways, for the sake of consistency I've planned to add serialization of the knn model (any predictor model has `toJson` and `saveAsJson` methods, it's better not to do any exception).

**Comment by jurrdb** [comment]
@gyrdym Seems like a sound decision to me. I'd be happy to deliver any feedback!

**Comment by gyrdym** [comment]
@jurrdb Hi, it's been a long while since we discussed KNN models persistence, but finally I've added the functionality to the library - https://github.com/gyrdym/ml_algo/pull/166, it's possible now to save the models to a json file and restore them from the file.
