### ISSUE TITLE
Integrate python algorithms like xgboost using ffi

### ISSUE THREAD

**Issue by deadsoul44** [gyrdym/ml_algo#192]
This is a great project. I started to hate Python after using Dart with Flutter. I realized that I am still googling every basic stuff when using Python whereas with Dart it just takes microseconds to find the right method after putting dot. I wonder if it is possible to integrate popular machine learning algorithms like xgboost in Dart using FFI.

Thanks a lot for creating this library.

**Comment by gyrdym** [comment]
@deadsoul44 Hi! Thank you very much for your attention to the project! Yes, I agree, Dart is a beautiful programming language, no doubt. Yes, it's possible, but it would take really much time. Anyway, I have some plans to integrate ensemble algorithms like xgboost, maybe in a couple of months, I will start to work on this.

**Comment by deadsoul44** [comment]
Are you going to implement it from scratch in Dart or are you going to use FFI?

**Comment by gyrdym** [comment]
@deadsoul44 I think so, I'll consider FFI
