### ISSUE TITLE
Dart package listed under https://ml-algo.com/ , but no website there

### ISSUE THREAD

**Issue by zathras** [gyrdym/ml_algo#202]
Going to http://ml-algo.com, I get a Namecheap page saying the domain was recently registered.  The https version of that URL is registered at https://pub.dev/publishers/ml-algo.com/packages .  I'd recommend at least setting up a quick one-page website there with a link back to github - it helps with people like me, who try to look into a publisher before using a package off pub.dev :-)

**Comment by gyrdym** [comment]
@zathras hi, thank you for the suggestion :) The page is in progress right now
