### ISSUE TITLE
Reinforcement Learning

### ISSUE THREAD

**Issue by point-source** [gyrdym/ml_algo#235]
How difficult would it be to implement RL aglorithms / provide support for RL-based training methods? Is this on the roadmap by any chance?

**Comment by gyrdym** [comment]
Hi @point-source,

Reinforcement Learning is on the roadmap, but it is in the long-term plans. So far I focused on supervised and unsupervised learning algorithms.

**Comment by point-source** [comment]
That's great news! I'll keep an eye on the repo. Thanks

**Comment by gyrdym** [comment]
Thank you for your interest in the library.
