### ISSUE TITLE
Random forest implementation

### ISSUE THREAD

**Issue by Maro1F431** [gyrdym/ml_algo#236]
Hello !
I have been using flutter on my free time and found out about this interesting library.
As a side project, I would like to add an implementation of the random forest to the library via a pull request. 
Would you be interested ?

**Comment by gyrdym** [comment]
@Maro1F431 Hello!

Thank you for your interest in the library. Random Forest is a too complicated algorithm, I'd like to recommend you something less difficult to begin with, for instance, you may implement [f-score](https://en.wikipedia.org/wiki/F-score) metric. What do you think about it?

**Comment by Maro1F431** [comment]
Seems good to me !

**Comment by gyrdym** [comment]
@Maro1F431 Great! So please visit the [directory](https://github.com/gyrdym/ml_algo/tree/master/lib/src/metric/classification). You can use any of the metrics as an example. I think it's better to start with the f1 score.
