### ISSUE TITLE
Can use for Multiple Regression Analysis?

### ISSUE THREAD

**Issue by lkc33** [gyrdym/ml_algo#254]
Hi,
Can any of the module uses for Multiple Regression Analysis?

Thanks

**Comment by gyrdym** [comment]
@lkc33 hello,

yes, you may use any of Linear regression models, e.g. [LinearRegressor](https://pub.dev/documentation/ml_algo/latest/ml_algo/LinearRegressor/LinearRegressor.html) class. 

you can find an example [here](https://medium.com/@ilgyrd/a-gentle-introduction-to-linear-regression-the-dart-way-9750214e6fa2)
