### ISSUE TITLE
demo & API deployment 

### ISSUE THREAD

**Issue by flutter-painter** [gyrdym/ml_algo#255]
Hi Llia,
First a huge thanks for this work and your extra-pedagogical tone and positive attitude !
I practiced a bit of ML, trained a couple of models and now I would like others to use them, e.g. ship a demo.

I can plug this logic in a Flutter app, which is great but too tedious,
I can also build a Dart binary / a console app, but it won't pass security,
In most use cases "users/clients/bosses" would need to request this model from the browser (e.g. hugging-face space)
or at least through a web API.

I would consider building on a simple server package then use [globe](https://globe.dev/) to ship it painlessly, and.. finally they could test it using postman !

Would you recommend another approach ?

**Comment by Jensen-holm** [comment]
I believe that you could save the model as a json file using the `model.toJson("<file-path>.json")` function if you would like a model that you have trained to run on device without the need to connect to the internet.

Correct me if I am wrong, I am new to this project

**Comment by flutter-painter** [comment]
Well the device would need a dart / Flutter app to run it, making demo complicated...

________________________________

**Comment by gyrdym** [comment]
Hi everyone,

Thank you for your interest in ml_algo!

To be honest, I have no idea, what is the best option for deployment for demo purposes :)

I need to think it over, I'll take a look at `globe`, it looks promising.

**Comment by flutter-painter** [comment]
Thank you for your reply,
On second thought...
After messing a bit with dart frog, I prefer a more manual approach, too many things occur beyond the hood and the files/route management bugs me.

In addition I fear that globe's freemium will not last long.
It is a common marketing approach to lower the barrier and then move to a pay as you go plan for all. This is what [fly.io](https://fly.io/docs/about/pricing/) did.

So I would favor [top-shelf](https://github.com/KLEAK-Development/top_shelf) 👨‍🍳
It brings simplicity to [shelf](https://github.com/dart-lang/shelf) and provides out of the box authent and sqlite demo.
There is a Dockerfile in the example to deploy it on any cloud provider.
Google Cloud provides 2M requests / month for free on Cloud Run, and I believe this one will last.

Reverting to the repo's topic if you deem it useful. I would be happy to document this deployment process in the context of a simple ML service

**Comment by gyrdym** [comment]
@flutter-painter I' ll take a look at the tools you proposed this weekend.

**Comment by gyrdym** [comment]
@flutter-painter

I have reviewed both [shelf](https://github.com/dart-lang/shelf) and [top_shelf](https://github.com/KLEAK-Development/top_shelf).

To confirm that we're on the same page: are you proposing to create a web application using a tool like [top_shelf](https://github.com/KLEAK-Development/top_shelf) where users (e.g., clients or managers) can test ml_algo in real-time? Specifically, they would be able to select datasets, adjust model hyperparameters, and initiate model training directly in the browser.

If that’s the case, I believe it could be quite useful. You mentioned that you'd be happy to document the deployment process—this sounds excellent. I'd be very interested in learning more about how to deploy a simple ML service. Is there any assistance you need from my side?

**Comment by flutter-painter** [comment]
Hi Llia,
I really like your idea but this sounds like a hugging-face clone and I'm not up for it 😅

What I had in mind was "just" to demo a live model : 
Let's picture a web page with two TextFields to type the dimensions of the Iris flower, press **infer** button and see the page display the Iris' species.
I think seeing a web demo and knowing how to deploy it could spark ideas

**Comment by flutter-painter** [comment]
Hello @gyrdym,

On third thought, for such use case no need for an API !
We can use Dart Web Assembly (wasm) support to bring **ml** logic into a simple html/js website.
I built such demo with the iris decision tree example in https://github.com/gyrdym/ml_algo/pull/257

As you can see in the screenshot below once user typed iris dimensions and click the button, the result is displayed.
It is possible to use ready-made models as long as they are not imported using dart:io but as a const String.
This demo is stark, but if you are comfortable with html/css/js you could build further to allow user to select datasets, adjust params, and train models. 

Instead of locking one in Flutter-web, this approach makes it possible to use other light ml models besides Dart, provided they are wasm compatible.

<img width="770" alt="screenshot" src="https://github.com/user-attachments/assets/22224952-e5a6-4fd3-b022-82e6bc0ca645">

**Comment by gyrdym** [comment]
@flutter-painter 

Hello,

Looks awesome! I'm glad to hear that the demo is getting simpler with wasm.

I'll review your PR on Thursday. Thanks a lot for your contribution!
